// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAELzghKssn-Lcxp-SaR7LbwMVmON0JF3I',
    appId: '1:655035274205:web:028b10dba84479c7ed9c34',
    messagingSenderId: '655035274205',
    projectId: 'hevento-7371e',
    authDomain: 'hevento-7371e.firebaseapp.com',
    storageBucket: 'hevento-7371e.appspot.com',
    measurementId: 'G-7C9DVT1HC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApNkCedCS1_2oMcbqwIT7wNMj2pkG8nhE',
    appId: '1:655035274205:android:c9ad51786d9cd3f9ed9c34',
    messagingSenderId: '655035274205',
    projectId: 'hevento-7371e',
    storageBucket: 'hevento-7371e.appspot.com',
  );
}
